str_play_with_this_country = ["Играть за эту страну!", "Play with this country!"] 
str_about_app = ["О программе", "About application"]
str_activate_tech = ["Активировать\nметод!", "Activate\nmethod"]
str_capital = ["Столица", "Capital"]
str_carryover = ["Перенос  ", "Transfer  "]

str_change_resolution = ["Выбор разрешения\nэкрана", "Change resolution\nof screen"]
str_check = ["Проверить", "Check"]
str_close_game = ["Закрыть игру", "Close game"]
str_close_info = ["Закрыть информацию о странах", "Close info"]
str_close_manual = ["Закрыть  правила", "Close rules"]
str_close_sett = ["Закрыть настройки","Close settings"]
str_close_window = ["Закрыть окно", "Close window"]
str_coef_carryover = ["Коэффициент переноса", "Carryover"]
str_coins = ["монет", "coins"]

str_deactivate_tech = ["Деактивировать\nметод", "Deactivate\nmethod"]
str_e = ["Ввод", "Enter"]
str_end_step = ["Завершить ход", "End turn"]
str_enter = ["Готово!", "Enter"]
str_enter_code = ["Ввести код", "Enter code"]
str_get_tech = ["Освоить метод!", "Get the method!"]

str_gotten_tech = ["Освоено!", "Gotten!"]

str_money = ["Монеты", "Coins"]
str_multichoice = ["Множественный\nвыбор", "Multichoice"]  
str_numer_of_step = ["Номер хода", "Number of step"]
str_pay = ["Потратить!", "Pay"]
str_price_of_get = ['Цена освоения', "Development cost"]
str_price_of_invest = ['Стоимость инвестиции', 'Investition cost']
str_price_of_research = ['Цена исследования', 'Research cost']
str_open_country_info = ['Информация\n о странах', 'Country info']
str_open_sett = ["Открыть настройки", "Open settings"]
str_panel_of_tech = ["Панель методов", "Methods panel"]

str_proinvest = ["Проинвестировать!", "Invest!"]

str_redraw = ["Перерисовать", "Redraw"]
str_researched = ["Исследовано!", "Researched"]
str_research_tech = ["Исследовать технологию!", "Research\ntechhology!"]
str_straph_points = ["Штрафные очки", "Penalty points"]
str_want_to_invest_again = ["ghjfk", "ufiyyoiu"]
str_win_points = ["Победные очки", "Victory points"]